spring:
  application:
    name: calculation_engine

  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5432/BankingSystemDB
    username: lauren
    password: dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10

# ⬇⬇⬇ CUSTOM CONFIG (outside spring)
rabbitmq:
  exchange:
    calculation: calculation.exchange

  queue:
    calculation:
      rwa: calculation.rwa.queue
      car: calculation.car.queue
      lcr: calculation.lcr.queue
      npl: calculation.npl.queue
      ecl: calculation.ecl.queue

    snapshot: calculation.snapshot.queue
    notification: calculation.notification.queue
