server:
  port: 3000

spring:
  application:
    name: calculation_engine

  datasource:
    url: jdbc:postgresql://localhost:5432/BankingSystemDB
    username: lauren
    password: dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled : false

  rabbitmq:
    host:  192.168.104.160
    port: 5672
    username: lauren
    password: dev
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10


rabbitmq:
  exchange:
    calculation: calculation.exchange

  queue:
    calculation:
      rwa: calculation.rwa.queue
      car: calculation.car.queue
      lcr: calculation.lcr.queue
      npl: calculation.npl.queue
      ecl: calculation.ecl.queue

    snapshot: calculation.snapshot.queue
    notification: calculation.notification.queue
