
spring:
  application:
    name: calculation_engine

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled : false

  rabbitmq:
    host:  ${RABBITMQ_HOST_IP}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10


rabbitmq:
  exchange:
    calculation: calculation.exchange

  queue:
    calculation:
      rwa: calculation.rwa.queue
      car: calculation.car.queue
      lcr: calculation.lcr.queue
      npl: calculation.npl.queue
      ecl: calculation.ecl.queue

    snapshot: calculation.snapshot.queue
    notification: calculation.notification.queue
